language: go

matrix:
  fast_finish: true

go:
  - 1.4
  - 1.5

before_install:
  - go get github.com/codahale/hdrhistogram
  - go get golang.org/x/net/context
  
install:
  - go build .

script:
  - go test -v

notifications:
  - email: false